CREATE DATABASE db_usinabeer;
USE db_usinabeer;

CREATE TABLE tb_produtos(
	CODIGO INT AUTO_INCREMENT,
    NOME VARCHAR (255),
    PRECO_CUSTO FLOAT,
    PRECO_VENDA FLOAT,
    QUANTIDADE INT,
    FORNECEDOR VARCHAR (255),
    
	PRIMARY KEY (CODIGO)
);

INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("ANDINA BRASIL", "COCA-COLA 2L", 6.89, 8.90, 200);
INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("ANDINA BRASIL", "FANTA UVA 2L", 6.39, 7.90, 200);
INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("JOHN WALKER", "WHISKY 15 YEARS", 768.89, 980.25, 10);
INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("JOHN WALKER", "REDLABEL WORLD CUP", 398.87, 500.21, 200);
INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("JOHN WALKER", "JACK DANIELS", 400.00, 789.45, 5);
INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("ELITE BEER", "AMARULA AFRYCA", 480.87, 499, 2);
INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("PIRASSUNUNGA", "AGUARDENTE 51", 8.89, 12.90, 50);
INSERT INTO tb_produtos (FORNECEDOR, NOME, PRECO_CUSTO, PRECO_VENDA, QUANTIDADE)
VALUES ("GRAU DISTRIBUIDORA", "RUM MONTILA", 20.89, 29.90, 100);

#SELECT * FROM tb_produtos;
SELECT * FROM tb_produtos WHERE PRECO_VENDA > 500;
SELECT * FROM tb_produtos WHERE PRECO_VENDA < 500;

UPDATE tb_produtos SET QUANTIDADE = 5 WHERE CODIGO = 9;
 SELECT * FROM tb_produtos;